### ISSUE TITLE
Configuration of init script... blocks server install

### ISSUE THREAD

**Issue by nnmathieugrin** [dynaTrace/Dynatrace-Puppet#14]
The error appears...
Error: Syntax error at '.'; expected ')' at /tmp/vagrant-puppet-3/modules-0/dynatrace/manifests/resource/configure_init_script.pp:36
Why are the init.d files furnished by the installer not used?

**Comment by metmajer** [comment]
Thanks @nnmathieugrin for reporting. The syntax error appeared in Puppet versions <= 3.8 since I introduced the use of $params.merge() with $params being a Hash that is not yet supported in these versions. I have fixed this error by resorting to Puppet stdlib's merge() in Commit 2887869.
