### ISSUE TITLE
require_relative issue

### ISSUE THREAD

**Issue by alfredodeluca** [Dynatrace/Dynatrace-Puppet#22]
Hi Martin. Just reporting this issue. All the time I install the modules (either server,collector etc) I got this error. They are related to jar.rb and tar.rb
Any way to fix this? I had to manually change require_relative to require to fix but not sure if it's the right way.

Error: Could not autoload puppet/provider/dynatrace_installer/tar: undefined method `require_relative' for main:Object
Error: Could not autoload puppet/type/dynatrace_installer: Could not autoload puppet/provider/dynatrace_installer/tar: undefined method `require_relative' for main:Object
Error: /Stage[main]/Dynatrace::Role::Server/Dynatrace_installation[Install the Dynatrace Server]: Could not evaluate: Could not autoload puppet/type/dynatrace_installer: Could not autoload

**Comment by metmajer** [comment]
@alfredodeluca: it seems like you are using a Ruby version that does not support the `require_relative` method. This version has been added with Ruby 1.9. Which version are you using?

I'd be interested in learning about your use-case around automatic deployments of the Dynatrace server. Interested in having a quick discussion? My email address is stated on my GitHub profile page. Thanks!

**Comment by alfredodeluca** [comment]
Hi Martin. I am using Ruby 1.8.7 which it comes by default from Puppet server packages. 
I will send an email later on about my testing with DT and Puppet
