### ISSUE TITLE
The dynatrace installation code gets executed each Puppet run.

### ISSUE THREAD

**Issue by MG2R** [Dynatrace/Dynatrace-Puppet#25]
I'm having trouble finding out what is causing this. Puppet run debug output shows the following for each and every Puppet run:

`Debug: Exec[Check for the presence of /var/opt/lib/pe-puppet/dynatrace/dynatrace.jar](provider=posix): Executing check '/usr/bin/test -e /var/opt/lib/pe-puppet/dynatrace/dynatrace.jar'
Debug: Executing '/usr/bin/test -e /var/opt/lib/pe-puppet/dynatrace/dynatrace.jar'
Debug: Exec[wget-Download http://<our server>/various/dynatrace/6.3/dynatrace-linux-x64.jar to /var/opt/lib/pe-puppet/dynatrace/dynatrace.jar](provider=posix): Executing check 'test -s '/var/opt/lib/pe-puppet/dynatrace/dynatrace.jar''
Debug: Executing 'test -s '/var/opt/lib/pe-puppet/dynatrace/dynatrace.jar''
Debug: Executing 'jar -tf /var/opt/lib/pe-puppet/dynatrace/dynatrace.jar | grep -e 'init.d' | tail -n 1'
Debug: Executing 'jar -xf /var/opt/lib/pe-puppet/dynatrace/dynatrace.jar init.d/dynaTracezRemoteAgent'
Debug: Executing 'grep -e 'DT_HOME=' init.d/dynaTracezRemoteAgent | cut -d'=' -f2 | xargs basename'
Notice: /Stage[main]/Dynatrace::Role::Server/Dynatrace_installation[Install the Dynatrace Server]/ensure: created
Debug: /Stage[main]/Dynatrace::Role::Server/Dynatrace_installation[Install the Dynatrace Server]: The container Class[Dynatrace::Role::Server] will propagate my refresh event
Debug: Executing '/sbin/service dynaTraceServer status'
Debug: Executing '/sbin/chkconfig dynaTraceServer'
Debug: Class[Dynatrace::Role::Server]: The container Stage[main] will propagate my refresh event
Debug: Executing '/sbin/service dynaTraceCollector status'
Debug: Executing '/sbin/chkconfig dynaTraceCollector'
Debug: Executing '/sbin/service dynaTraceAnalysis status'
Debug: Executing '/sbin/chkconfig dynaTraceAnalysis'
`

This is on RedHat 6.7 running PE 3.7.2

**Comment by metmajer** [comment]
Reason we are doing this is to check if the installer you've downloaded contains a version newer than what's already installed. Is this behavior causing you any issues?

**Comment by metmajer** [comment]
Important notice: Dynatrace is not installed with every Puppet run. The installer is unpacked to determine whether an installation has to be done based on an embedded version string.

If I will not hear from you in 7 days, I'll close this issue as invalid.

**Comment by MG2R** [comment]
Terribly sorry about the delay. I completely missed your previous reply, apparently.

The reason I made this bug report is because all nodes including the dynatrace code are showing up as "changed" in our Puppet Console. If a node isn't actually modified during a puppet run, the run should exit cleanly and thus the node should have a status "unchanged".

**Comment by metmajer** [comment]
Hi @MG2R. Apparently, the same thing happened on my side, sorry 'bout that! I've labeled your issue as a bug. We'll look into this soon.

**Comment by jensdt** [comment]
Hi @metmajer, do you have an ETA for this already? We're also running into this issue and while it's not breaking anything, it is annoying that each Dynatrace node is marked as 'changed' every run.

**Comment by MarcinZejer** [comment]
Hi @jensdt, I'm sorry for delay. We started working on this in the lab so next week we should have some results to share.

**Comment by MarcinZejer** [comment]
Hi @jensdt, We published new version https://github.com/Dynatrace/Dynatrace-Puppet/releases/tag/v1.0.3 which should resolve that issue. 
Thanks,
Marcin

**Comment by MG2R** [comment]
This seems to have fixed the agent run statuses. Thanks!
